services:
  api:
    build: .
    container_name: user-service
    depends_on:
      - mongo
    environment:
      MONGO_URI: link mongo, poi facciamo
    ports:
      - "3000:3000"
    command: npm run start:dev

  mongo:
    image: mongo:6
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d