services:
  api:
    build: .
    container_name: user-service
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb+srv://nicolasimionato5_db_user:axxbKZgs4XhKmGHM@userservicedb.dgjf6lx.mongodb.net/dev-db
    ports:
      - "3000:3000"
    command: npm run start:dev

  mongo:
    image: mongo:6
    container_name: mongo-dev
    ports:
      - "27017:27017"