sonar.projectKey=HeptaCode-UniPD_UserService
sonar.organization=heptacode-unipd
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.module.ts,**/main.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=test/coverage/lcov.info